### ISSUE TITLE
A mountable version

### ISSUE THREAD

**Issue by balauru** [c4mprod/grape-batch#3]
It will be nice if we could also have a mountable version of this, it will show up in the swagger documentation and will speed things up as there isn't another middleware that needs to be checked.

**Comment by balauru** [comment]
Do you think is a good idea? Shall I try to work on this and send a pull request.

So far in my app I have:

```ruby
module API
  module Resources
    class Batch < Grape::API
      resource :batch do
        post do
          Grape::Batch::Base.new(OmniApi::App.instance).batch_call(env)
        end
      end
    end
  end
end
```

**Comment by L-Oto** [comment]
We kinda missed your post, sorry! Your proposition is interesting, give us some time to process.

**Comment by balauru** [comment]
No problem, I am using the above work around, works great, in my use case I also need the `before` and `after` functions that grape provides.

**Comment by L-Oto** [comment]
I would be nice if you could make a pull request out of this. You also will have to update the documentation and the unit tests, what do you say?

**Comment by balauru** [comment]
@L-Oto sorry for the late reply, will work on this and send a pull request.
