### ISSUE TITLE
Add to Grape projects

### ISSUE THREAD

**Issue by dblock** [c4mprod/grape-batch#5]
This is an awesome gem. Please add to https://github.com/ruby-grape/ruby-grape.github.io/blob/master/projects/index.md, thanks!

**Comment by L-Oto** [comment]
I tried to push my modification but it seems there's a permission issue... Any idea? :)

**Comment by dblock** [comment]
Please make a pull request

**Comment by L-Oto** [comment]
I'm sorry but I can't push my branch to make a proper pull request:
ERROR: Permission to ruby-grape/ruby-grape.github.io.git denied to L-Oto
I'm puzzled :)

**Comment by dblock** [comment]
Check out https://github.com/ruby-grape/ruby-grape.github.io/blob/master/CONTRIBUTING.md? You should fork the project and push to your fork, not to the upstream repo, then make a PR :)

**Comment by L-Oto** [comment]
Thank you for your patience. My PR is waiting to be merged :)
