### ISSUE TITLE
Unable to reach /batch endpoint

### ISSUE THREAD

**Issue by anothermh** [c4mprod/grape-batch#6]
I am trying to use grape-batch with a grape API. No matter how I configure the gem I get the same result when I try to hit the batch endpoint:

`No route matches [POST] "/batch"`

To test this, I created a new Rails app from scratch and added only `grape` and `grape-batch`, then used the examples from the README for each. The repository is available at https://github.com/anothermh/grape-batch-example and it has a very simple commit history showing the changes made. I am using grape v0.14.0 and grape-batch v2.1.1 with rack v1.6.4 and Rails v4.2.5.

I am able to reach the example Grape API at localhost:3000/api/statuses, but localhost:3000/batch and localhost:3000/api/batch both return `No route matches [POST]`.

How do you make the `/batch` endpoint available?

**Comment by anothermh** [comment]
Here is the output of `rake middleware`:

```
use Rack::Sendfile
use ActionDispatch::Static
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007fcda78d1450>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use WebConsole::Middleware
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Grape::Batch::Base
run GrapeBatchExample::Application.routes
```

**Comment by anothermh** [comment]
I was able to mount the `/batch` endpoint by adding this line to https://github.com/anothermh/grape-batch-example/blob/master/app/api/twitter/api.rb#L4:

```ruby
mount Grape::Batch::Base.new(Twitter::API) => '/batch'
```

Now I am able to hit the `/batch` endpoint and submit batch requests:

```
POST /batch HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"requests":[{"method":"GET","path":"/api/statuses"},{"method":"GET","path":"/api/users"}]}
```

And receive responses:

```
[{"success":{"example_status":"example status value"}},{"success":{"example_user":"example user value"}}]
```

I recommend adding something to the README for Rails projects about adding the line `mount Grape::Batch::Base.new(Twitter::API) => '/batch'`.

**Comment by L-Oto** [comment]
I'm happy you finally found a solution by yourself but I'm also surprised you had the problem in the first place. I won't be able to look into it right now but I definitely will by the end of the week.

**Comment by L-Oto** [comment]
I forked your project and apply some small changes to the grape-batch setup : https://github.com/L-Oto/grape-batch-example.

I'm using "postman" a google chrome extension as REST client, and I've been surprised because without your modification everything worked as expected. Still I applied some small updates and I will update the documentation.

**Comment by anothermh** [comment]
There are no new commits on your repo to check. It's even with the original repo.

**Comment by L-Oto** [comment]
My mistake, I forgot to push my code. I'll do it tomorrow when I'll have access to my computer again.
